/**
 * @NApiVersion 2.1
 */
define([], () => {
    const RECORDS = {}

    RECORDS.CONFIG = {}
    RECORDS.CONFIG.ID = 'customrecord_id'
    RECORDS.CONFIG.FIELDS = {}
    RECORDS.CONFIG.FIELDS.CLIENTE = 'Cliente'
    RECORDS.CONFIG.FIELDS.DATE = 'Date'

    RECORDS.TRANSACTIONS = {}

    RECORDS.TRANSACTIONS.PURCHASE_ORDER = {}
    RECORDS.TRANSACTIONS.PURCHASE_ORDER.INTERNAL_ID = 'internalid'
    RECORDS.TRANSACTIONS.PURCHASE_ORDER.TRANID = 'tranid'
    RECORDS.TRANSACTIONS.PURCHASE_ORDER.ITEM = 'item'
    RECORDS.TRANSACTIONS.PURCHASE_ORDER.QUANTITY = 'quantity'
    RECORDS.TRANSACTIONS.PURCHASE_ORDER.UNIT = 'unit'
    RECORDS.TRANSACTIONS.PURCHASE_ORDER.LOT = 'serialnumbers'
    RECORDS.TRANSACTIONS.PURCHASE_ORDER.TRANDATE = 'trandate'
    RECORDS.TRANSACTIONS.PURCHASE_ORDER.QUANTITYUOM = 'quantityuom'
    RECORDS.TRANSACTIONS.PURCHASE_ORDER.QUANTITY_RECEIVED = 'quantityshiprecv'


    return { RECORDS }
});
  